MIN_CHARITY_PROJECT_NAME_CHAR = 1
MAX_CHARITY_PROJECT_NAME_CHAR = 100
MIN_CHARITY_PROJECT_DESCRIPTION_CHAR = 1
MIN_PASSWORD_LENGTH = 3
INVESTED_START_AMOUNT = 0

SHEET_TITLE_FORMAT = "%Y/%m/%d %H:%M:%S"
